#pragma once

#include <memory>
#include <string>
#include <unordered_set>
#include <vector>

#include "PuzzleConfig.h"

class DisassemblyGraph
{
public:
    // puzzle is either generated by the PuzzleGenerator or imported from a puzzle file
    // all data will be cleared before each generation / import
    bool ImportPuzzle(const std::string &puzzleFilePath);

    // config operations
    void RenderConfig(int configID, Shader &shader, VertexBuffer &voxelModel);
    void CalculateNeighborConfigs(int configID, std::vector<std::shared_ptr<PuzzleConfig>> &neighborConfigs);
    void BuildKernelDisassemblyGraph();
    void DisassembleGraph();

    // queries
    PuzzleConfig &GetPuzzleConfig(int configID);
    int GetPuzzleConfigNum() const;

    // tests
    void Test_AddAllNeighborConfigs(int configID); // this action doesn't maintain edges!

private:
    std::vector<std::unordered_set<int>> _GraphEdges;
    std::vector<std::shared_ptr<PuzzleConfig>> _GraphNodes;
    std::vector<int> _TargetNodeIDs;
};
