#pragma once

#include <memory>
#include <set>
#include <string>
#include <vector>

#include "PuzzleConfig.h"

class DisassembleGraph
{
public:
    // puzzle is either generated by the PuzzleGenerator or imported from a puzzle file
    // all data will be cleared before each generation / import
    bool ImportPuzzle(const std::string &puzzleFilePath);

    // config operations
    void RenderConfig(int configNo, Shader &shader, VertexBuffer &voxelModel);
    void CalculateNeighborConfigs(int configNo, std::vector<std::shared_ptr<PuzzleConfig>> &neighborConfigs);

    // queries
    PuzzleConfig &GetPuzzleConfig(int configNo);

    // tests

private:
    std::vector<std::set<int>> _GraphEdges;
    std::vector<std::shared_ptr<PuzzleConfig>> _GraphNodes;
};
